name: code_notes_backend dev

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.12.0
        with: 
          distribution: 'temurin'
          java-version: '17'
      - name: Start db
        run: docker compose -f 'docker-compose.dev.yml' up db -d      
      - run: gradle clean build