name: test

run-name: ${{ github.event.head_commit.message }}
on:
    workflow_dispatch:

jobs:
    deploy_to_server:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2

            - name: Install OpenVPN
              run: |
                  sudo apt update
                  sudo apt install -y openvpn openvpn-systemd-resolved
            - name: Connect to VPN
              uses: kota65535/github-openvpn-connect-action@v3
              with:
                  config_file: .github/workflows/config.ovpn
                  client_key: ${{ secrets.OPEN_VPN_PRIVATE_KEY }}

            - name: Verify connection to target server
              run: |
                    ping -c 3 ${{ vars.SSH_HOST }}
                    nc -zv ${{ vars.SSH_HOST }} 22
                    
            - name: Copy some files to remote first
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ vars.SSH_HOST }}
                  username: ${{ secrets.SSH_USER_NAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  source: writeToEnvFile.sh
                  target: ./${{ vars.SSH_TARGET_FOLDER }}
                  debug: true